name: system information actions
on: 
  push:
    branches: [master]
jobs:
  sysinfo-workflow-actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [21.0.0]
    steps:
      - run:  actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test
     